name: Create and publish a package
on:
  release:
    types: [created]
jobs:
  # run-npm-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: npm install and build webpack
  #       run: |
  #         npm install
  #         npm run build
  publish-npm:
    # needs: run-npm-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
